include:
  - project: 'shared/gitlab-ci-includes'
    ref: main
    file:
      - '/base.yml'
      - '/pypi-packages.yml'
      - '/debian-packages.yml'
      - '/python.yml'

variables:
  APTLY_BASE_REPOSITORY: common

stages:
  - test
  - build
  - publish

# unit test and feature test:
#   stage: test
#   image: python:3.11
#   script:
#     - !reference [.add repositories, script]
#     - apt-get -y install python3-cyberfusion-common python3-requests python3-certifi
#     - pip install --no-cache-dir -r requirements/test.txt
#     - cp cyberfusion.ci.cfg cyberfusion.cfg
#     - PYTHONPATH=$CI_PROJECT_DIR/src:/usr/lib/python3/dist-packages pytest -n 10 -vvv --cov-branch --cov=cyberfusion.AptlyApiCli --cov-config=.coveragerc --junitxml=report-pytest.xml
#   artifacts:
#     reports:
#       junit: report-*.xml
